### ISSUE TITLE
Migrate to embedding v2

### ISSUE THREAD

**Issue by hnvn** [hnvn/flutter_image_cropper#119]
https://github.com/flutter/flutter/wiki/Experimental:-Create-Flutter-Plugin

**Comment by Boehrsi** [comment]
Hi, is there already a release plan for the embedding v2 update? Right now, if an app is updated, the plugin isn't working. Due to the null check against `registrar.activity()` in https://github.com/hnvn/flutter_image_cropper/blob/master/android/src/main/java/vn/hunghd/flutter/plugins/imagecropper/ImageCropperPlugin.java#L24 which is always null with the v2 embedding, the plugin isn't register and will respond to calls with with:
```
2020-01-16 13:41:39.098 13054-13201/com.openxchange.oxcoi.dev E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method cropImage on channel plugins.hunghd.vn/image_cropper)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      ImageCropper.cropImage (package:image_cropper/src/cropper.dart:103:24)
    <asynchronous suspension>
    #2      ProfileAvatar.build._getNewAvatarPath (package:ox_coi/src/widgets/profile_header.dart:111:49)
    <asynchronous suspension>
    #3      ProfileAvatar.build._editPhoto.<anonymous closure>.<anonymous closure> (package:ox_coi/src/widgets/profile_header.dart:138:49)
    #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
    #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
    #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
    #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
    #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
    #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
    #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
    #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #16     _rootRunUnary (dart:async/zone.dart:1138:13)
    #17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #19     _invoke1 (dart:ui/hooks.dart:273:10)
    #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```
I just saw you already have a branch for the issue, is there something I could assist with?

Btw. thanks for the nice plugin @hnvn :+1:

**Comment by Boehrsi** [comment]
Just tested the feature branch and everything works fine 👍 . Is there already a release planned for a version including the v2 embedding?

**Comment by hnvn** [comment]
I am going to publish it this weekend

**Comment by Boehrsi** [comment]
Thanks a lot 👍 .

**Comment by hnvn** [comment]
v1.2.0 has landed
