### ISSUE TITLE
[Android] NullPointerException thrown with 1.2.1

### ISSUE THREAD

**Issue by njovy** [hnvn/flutter_image_cropper#139]
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.setMethodCallHandler(io.flutter.plugin.common.MethodChannel$MethodCallHandler)' on a null object reference
       at vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onDetachedFromEngine(ImageCropperPlugin.java:1)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:23)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:26)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:1)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:3)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:2)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:14)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:3)
       at android.app.Activity.performDestroy(Activity.java:7680)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4672)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4705)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
Above is a stacktrace of this exception. 
I use this library in production and I get this exception in my crashlytics from some users.

**Comment by hnvn** [comment]
Looks like you haven’t migrate your project to Flutter v1.12 yet, see document for detail

**Comment by njovy** [comment]
@hnvn I am using the 1.12.6 flutter and migrated to embedding v2. If mine wasn't migrated completely, shouldn't it crash more often?

**Comment by hnvn** [comment]
Does it happen on the [example ](https://github.com/hnvn/flutter_image_cropper/tree/master/example)project?

**Comment by njovy** [comment]
@hnvn The example project doesn't represent all the possible cases that can happen with this plugin. This plugin mainly depends on native-side code to crop so a lot of unexpected scenarios can happen. I wasn't able to reproduce this on my hand but this exception is getting thrown from users so I copied here for further investigation. Right now this is the only exception that my app received from crashlytics. Unlike normal crashes, 94% of devices were in background state when it's crashed so I wouldn't say it happens in a normal case.

**Comment by hnvn** [comment]
OK, I will try to look at it

**Comment by njovy** [comment]
I've been using this library in production since 1.1.0 and this was definitely a new exception thrown by users after update to 1.2.1 so I am sure this is related to flutter embedding v2 which is fairly new.
Thank you for all your hard work and thank you in advance!

**Comment by kinex** [comment]
I guess this would fix it:
```java
  @Override
  public void onDetachedFromEngine(FlutterPluginBinding binding) {
    if (channel != null) {
        channel.setMethodCallHandler(null);
        channel = null;
    }
  }
```
Issue may be related to https://github.com/flutter/flutter/issues/48202
Shortly: `onAttachedToEngine `may be called twice. I didn't verify this from logs but it probably means that also `onDetachedFromEngine `may be called twice.

**Comment by misterfifi1** [comment]
Hi, I have the same issue, can I help you to fix it?
