### ISSUE TITLE
Error on CI / CD build - any Version ! - image_cropper.podspec :  issue

### ISSUE THREAD

**Issue by Beautylivery** [hnvn/flutter_image_cropper#185]
Hi....

i am not sure how this error really appears. But i could recreate it while building on VS AppCenter while it is not appearing on my local machines build.

but it seems that the image_cropper.podspec always (in all Versions tried 1.2.1 and 1.2.2 and latest) has the variable `s.version          = '0.0.3' ` while the content clearly changes from s.dependency 'TOCropViewController', '2.5.3' to s.dependency 'TOCropViewController', '2.5.4' 

but s.dependency 'TOCropViewController', '2.5.4' is currently causing mayor issues. 
See reference: https://github.com/TimOliver/TOCropViewController/issues/424

Here is the error log
```

      CDN: trunk Relative path: Specs/f/9/9/AppCenter/3.3.3/AppCenter.podspec.json modified during this run! Returning local
      CDN: trunk Relative path: Specs/f/9/9/AppCenter/3.2.0/AppCenter.podspec.json modified during this run! Returning local
      CDN: trunk Relative path: Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json modified during this run! Returning local
    [!] CocoaPods could not find compatible versions for pod "TOCropViewController":
      In snapshot (Podfile.lock):
        TOCropViewController (= 2.5.3)

      In Podfile:
        TOCropViewController (= 2.5.3)

        image_cropper (from `.symlinks/plugins/image_cropper/ios`) was resolved to 0.0.3, which depends on
          TOCropViewController (~> 2.5.4)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `TOCropViewController` inside your development pod `image_cropper`.
       You should run `pod update TOCropViewController` to apply changes you've made.

    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
    /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<main>'

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install

##[error]The process '/bin/bash' failed with exit code 1
##[error]Bash failed with error: The process '/bin/bash' failed with exit code 1


```

It seems different to my local machine VS AppCenter uses CDN to load the pod data with references to the version.

As you can see in my log I already enforce Version TOCropViewController (= 2.5.3) which . but it does not make a difference it fails to the "correct" interpretation of the latest version 0.03 of image_cropper as it seems.

**Comment by hnvn** [comment]
See https://github.com/hnvn/flutter_image_cropper/issues/187#issuecomment-682729041

**Comment by Beautylivery** [comment]
Hey @hnvn,

your solution is not working in AppCenters CI CD Plattform ...

i modified my appcenter-post-clone.sh to

```
#!/usr/bin/env bash
#Place this script in project/ios/

# fail if any command fails
set -e
# debug log
set -x

#NEW Experimental Content CocoaPods
#sudo gem uninstall cocoapods
#sudo gem install cocoapods #-v 1.7.5
#pod setup

cd ..
git clone -b beta https://github.com/flutter/flutter.git
export PATH=`pwd`/flutter/bin:$PATH

flutter channel stable
flutter clean
flutter doctor

echo "Installed flutter to `pwd`/flutter"

#Try to deintegrate first
cd ios
pod deintegrate
rm -rf Podfile.lock
flutter pub get
pod install --repo-update

cd ..
flutter build ios --release --no-codesign

```

And i run into the following issue
```

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G2021, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
++ pwd
+ echo 'Installed flutter to /Users/runner/work/1/s/flutter'
+ cd ios
Installed flutter to /Users/runner/work/1/s/flutter
+ pod deintegrate
Deintegrating `Runner.xcodeproj`
Deleted 1 'Copy Pods Resources' build phases.
Deleted 1 'Check Pods Manifest.lock' build phases.
Deleted 1 'Embed Pods Frameworks' build phases.
- Pods_Runner.framework
Deleting Pod file references from project
- Pods-Runner.debug.xcconfig
- Pods-Runner.release.xcconfig
- Pods-Runner.profile.xcconfig
Deleted 1 empty `Frameworks` groups from project.
Removing `Pods` directory.

Project has been deintegrated. No traces of CocoaPods left in project.
Note: The workspace referencing the Pods project still remains.
+ rm -rf Podfile.lock
+ flutter pub get
Changing current working directory to: /Users/runner/work/1/s
Running "flutter pub get" in s...                                   5.8s
+ pod install --repo-update
cp: /Users/runner/work/1/s/flutter/bin/cache/artifacts/engine/ios/Flutter.framework: No such file or directory
cp: /Users/runner/work/1/s/flutter/bin/cache/artifacts/engine/ios/Flutter.podspec: No such file or directory
Updating local specs repositories
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`

CocoaPods 1.10.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.2


CocoaPods 1.10.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0.beta.2

Analyzing dependencies
[!] No podspec found for `Flutter` in `Flutter`

##[error]The process '/bin/bash' failed with exit code 1
##[error]Bash failed with error: The process '/bin/bash' failed with exit code 1
##[section]Finishing: Post Clone Script
##[section]Starting: Xcode build (signed)
```

Other approaches also did not work with changing the combination etc.... 
You solution works fine on the local machine , but i also dont get this error thrown.

**Comment by Beautylivery** [comment]
My suggestion would be still if you could change the s.version = '0.0.3'  in a previous release  ?

**Comment by Beautylivery** [comment]
THis one is no longer relevant

**Comment by rafaelcorbellini-egsys** [comment]
> pod install --repo-update

how you solve it?
