### ISSUE TITLE
java.lang.IllegalArgumentException: y + height must be <= bitmap.height()

### ISSUE THREAD

**Issue by JotaFerreira** [hnvn/flutter_image_cropper#20]
On android 6.0.1

Tested image

![image](https://user-images.githubusercontent.com/13682634/50683720-38299280-0ffa-11e9-88c6-f7c68946167b.png)

```
E/AndroidRuntime(30401): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=96, data=Intent { (has extras) }} to activity {br.com.klunkriative.avanti14/br.com.klunkriative.avanti14.MainActivity}: java.lang.IllegalArgumentException: Unsupported value: java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
E/AndroidRuntime(30401): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3717)
E/AndroidRuntime(30401): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3760)
E/AndroidRuntime(30401): 	at android.app.ActivityThread.access$1400(ActivityThread.java:153)
E/AndroidRuntime(30401): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
E/AndroidRuntime(30401): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(30401): 	at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime(30401): 	at android.app.ActivityThread.main(ActivityThread.java:5451)
E/AndroidRuntime(30401): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30401): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime(30401): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime(30401): Caused by: java.lang.IllegalArgumentException: Unsupported value: java.lang.IllegalArgumentException: y + height must be <= bitmap.height()
E/AndroidRuntime(30401): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:293)
E/AndroidRuntime(30401): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/AndroidRuntime(30401): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:208)
E/AndroidRuntime(30401): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.finishWithError(ImageCropperDelegate.java:99)
E/AndroidRuntime(30401): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:82)
E/AndroidRuntime(30401): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(30401): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(30401): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(30401): 	at android.app.Activity.dispatchActivityResult(Activity.java:6528)
E/AndroidRuntime(30401): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3713)
```

**Comment by njovy** [comment]
I ran into this issue as well.

**Comment by quantosapplications** [comment]
I ran into this issue as well.

**Comment by njovy** [comment]
@hnvn Any chance to investigate this? I think this happens because of a selected image but I believe there is a way to work around or throw an exception rather than crash. Thank you.

**Comment by hnvn** [comment]
Sounds like an issue of the native library, I think you might report it in its repository.
