### ISSUE TITLE
source file does not exist 

### ISSUE THREAD

**Issue by vijaybheda** [hnvn/flutter_image_cropper#227]
Unhandled Exception: 'package:image_cropper/src/cropper.dart': Failed assertion: line 81 pos 12: 'await File(sourcePath).exists()': is not true.

ImageCropper.cropImage (package:image_cropper/src/cropper.dart:81:12)

**Comment by kjxbyz** [comment]
flutter: \^[[38;5;196m│ 'package:image_cropper_platform_interface/src/method_channel/method_channel_image_cropper.dart': Failed assertion: line 72 pos 12: 'await File(sourcePath).exists()': is not true.<…>
flutter: \^[[38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;196m│ #0   _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)<…>
flutter: \^[[38;5;196m│ #1   _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)<…>
flutter: \^[[38;5;196m│ #2   MethodChannelImageCropper.cropImage (package:image_cropper_platform_interface/src/method_channel/method_channel_image_cropper.dart:72:12)<…>
flutter: \^[[38;5;196m│ #3   <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #4   SignatureUtil.cropImage (package:expert_planet/modules/mine/utils/signature_util.dart:117:25)<…>
flutter: \^[[38;5;196m│ #5   <asynchronous suspension><…>
flutter: \^[[38;5;196m│ #6   MineDialogs.showUploadBottomSheet.<anonymous closure>.<anonymous closure> (package:expert_planet/modules/mine/utils/mine_dialogs.dart:1511:38)<…>
flutter: \^[[38;5;196m│ #7   <asynchronous suspension><…>
