### ISSUE TITLE
Crash on Android in ReleaseMode

### ISSUE THREAD

**Issue by KSLiquid** [hnvn/flutter_image_cropper#249]
Hi,

thanks for the awesome plugin!
Sadly it works for me only in Debug mode.
In release mode I get the following error:

```
Fatal Exception: java.lang.NoSuchMethodError: No static method asAttributeSet(Lj/a/a/a;)Landroid/util/AttributeSet; in class Landroid/util/Xml; or its super classes (declaration of 'android.util.Xml' appears in /system/framework/framework.jar!classes2.dex)
       at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:21)
       at com.yalantis.ucrop.UCropActivity.onCreateOptionsMenu(UCropActivity.java:6)
       at android.app.Activity.onCreatePanelMenu(Activity.java:4109)
       at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
       at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
       at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
       at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:25)
       at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

My dependencies:
```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.4'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.4.1'
      }
}
```

Does anyone have an Idea how I can fix that?
Thanks alot!

**Comment by KSLiquid** [comment]
It works now - I have no Idea what was the problem.

**Comment by alexeyselina** [comment]
Issue happens for me. What can be done?

**Comment by VladShturma** [comment]
This also happened to me. This solution helped
https://stackoverflow.com/a/60631550/9581817
