### ISSUE TITLE
java.lang.NoSuchMethodError in release build APK

### ISSUE THREAD

**Issue by EsbenHojris-ebber** [hnvn/flutter_image_cropper#262]
I have added the activity in AndroidManifest.xml and migrated the project to v2 embedding. `ImageCropper.cropIamge()` works fine when debugging, but when I build a release APK I get the following stacktrace:

```
Fatal Exception: java.lang.NoSuchMethodError: No static method asAttributeSet(Li/a/a/a;)Landroid/util/AttributeSet; in class Landroid/util/Xml; or its super classes (declaration of 'android.util.Xml' appears in /system/framework/framework.jar!classes3.dex)
       at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:21)
       at com.yalantis.ucrop.UCropActivity.onCreateOptionsMenu(UCropActivity.java:6)
       at android.app.Activity.onCreatePanelMenu(Activity.java:4206)
       at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:2)
       at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:8)
       at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:2)
       at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:25)
       at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by furaiev** [comment]
The same issue. It seems like the reason is switching to [image_picker 0.8.0](https://pub.dev/packages/image_picker/changelog#080) with a **BREAKING CHANGE**: Changed storage location for captured images and videos to internal cache on Android, to comply with new Google Play storage requirements. This means developers are responsible for moving the image or video to a different location in case more permanent storage is required. Other applications will no longer be able to access images or videos captured unless they are moved to a publicly accessible location.

**Comment by Deepak-GP** [comment]
Somehow creating the app bundle through Android studio worked. 
Creating the release apk/app bundle in VS code resulted in this error (Although it was working previously. Don't know what caused this issue).
Maybe the gradle dependency had some issue.

Open the android folder of your flutter project in Android studio. Let the gradle update it's dependencies and wait for the indexing to be completed. Clean the project. Then generate the signed Bundle or APK.

**Comment by Recker4244** [comment]
This still has not been fixed?
