### ISSUE TITLE
Crash in Release mode with NoSuchMethodError

### ISSUE THREAD

**Issue by alexeyselina** [hnvn/flutter_image_cropper#268]
In release mode I get this error (debug mode works as should)

`Fatal Exception: java.lang.NoSuchMethodError: No static method asAttributeSet(Lj/a/a/a;)Landroid/util/AttributeSet; in class Landroid/util/Xml; or its super classes (declaration of 'android.util.Xml' appears in /system/framework/framework.jar!classes2.dex)`

There are closed issues here with the same problem but reporters say it was fixed by itself. 

After investigation found out that adding proguard file helps (problem with xml entities obfuscation)

Solution, how to fix: 
1.  add
`useProguard true`
`proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'`
to the app/src/gradle file in the 'release' section
2.  create if not created 'app/src/proguard-rules.pro' file and add following lines:
`-dontwarn org.xmlpull.v1.XmlPullParser`
`-dontwarn org.xmlpull.v1.XmlSerializer`
`-keep class org.xmlpull.v1.* {*;}`

After this release mode works for me.

**Comment by EsteveAguilera** [comment]
I've faced the same issue and this worked for me!
Maybe this should be added to the readme?

**Comment by mbfakourii** [comment]
I had a similar error like this
```
 Unable to start activity ComponentInfo{com.apadanaclinic.app/com.yalantis.ucrop.UCropActivity}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.yalantis.ucrop.o.a
```
Create a file in app/proguard-rules.pro that contains the problem will be solved
```
-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }
-keep class androidx.appcompat.** { *; }
```
the problem will be solved

**Comment by jomazao** [comment]
Similar issue on nexus 5x Android 8.1.0
Fatal Exception: java.lang.RuntimeException: Unable to start activity 
```
ComponentInfo{com.kargoo.kargooapp/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #27: Binary XML file line #46: Error inflating class ImageView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
