### ISSUE TITLE
Error when cropping image after zooming out 

### ISSUE THREAD

**Issue by piotrkovsy1331** [hnvn/flutter_image_cropper#413]
Hello im using Image_cropper package to crop images to custom aspectRatio. When I open image cropper and zoom out it is possible to take toolbar to out of the image borders. Then I get this PlatformException.

Exception has occurred.
PlatformException (PlatformException(crop_error, x must be >= 0, java.lang.IllegalArgumentException: x must be >= 0
	at android.graphics.Bitmap.checkXYSign(Bitmap.java:435)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:873)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:836)
	at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:165)
	at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:105)
	at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:37)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
, null))
![flutter_02](https://user-images.githubusercontent.com/35061489/231458081-be179e82-cbe3-486e-870c-37e10a84dac1.png)

![flutter_01](https://user-images.githubusercontent.com/35061489/231457956-e9f288e9-0fd3-4ae1-8e34-da85b76717fb.png)

I've configured image Cropper like this: 

final croppedImage = await _imageCropper.cropImage(
          sourcePath: result.files.first.path!,
          maxHeight: 44,
          maxWidth: 244,
          compressQuality: 80,
          aspectRatio: const CropAspectRatio(ratioX: 5.51, ratioY: 1),
          uiSettings: [
            AndroidUiSettings(
              toolbarTitle: 'Edytuj wymiary logo',
              toolbarColor: AppColors.redPastel,
              hideBottomControls: true,
              toolbarWidgetColor: Colors.white,
              lockAspectRatio: false,
              initAspectRatio: CropAspectRatioPreset.original,
            ),
            IOSUiSettings(
              title: 'Edytuj wymiary logo',
              aspectRatioLockEnabled: true,
            ),
          ],
        );

Is it possible to lock zooming out to the borders of an image or make image cropper go back to image size  ?

**Comment by CodingWithNobody** [comment]
Check this https://www.youtube.com/watch?v=1aRwxnX5nms
