### ISSUE TITLE
My app is crashing when trying to crop image

### ISSUE THREAD

**Issue by faizan2301** [hnvn/flutter_image_cropper#491]
Below is the error I'm getting while cropping the image
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{ae.urbanexpress.urbanexpress/com.yalantis.ucrop.UCropActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(20792): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3864)
E/AndroidRuntime(20792): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4006)
E/AndroidRuntime(20792): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
E/AndroidRuntime(20792): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(20792): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(20792): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
E/AndroidRuntime(20792): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20792): 	at android.os.Looper.loopOnce(Looper.java:240)
E/AndroidRuntime(20792): 	at android.os.Looper.loop(Looper.java:351)
E/AndroidRuntime(20792): 	at android.app.ActivityThread.main(ActivityThread.java:8377)
E/AndroidRuntime(20792): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20792): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(20792): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/AndroidRuntime(20792): Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime(20792): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
E/AndroidRuntime(20792): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
E/AndroidRuntime(20792): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
E/AndroidRuntime(20792): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:197)
E/AndroidRuntime(20792): 	at com.yalantis.ucrop.UCropActivity.onCreate(UCropActivity.java:126)
E/AndroidRuntime(20792): 	at android.app.Activity.performCreate(Activity.java:8397)
E/AndroidRuntime(20792): 	at android.app.Activity.performCreate(Activity.java:8370)
E/AndroidRuntime(20792): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)
E/AndroidRuntime(20792): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3837)
E/AndroidRuntime(20792): 	... 12 more
I/Process (20792): Sending signal. PID: 20792 SIG: 9
```
And this is my code to crop the image:
```
Future<XFile?> cropImage(XFile imageFile) async {
  CroppedFile? cropFile = await ImageCropper.platform.cropImage(
    sourcePath: imageFile.path,
    maxWidth: 1080,
    maxHeight: 1920,
    compressQuality: 80,
    aspectRatioPresets: [CropAspectRatioPreset.ratio4x3],
    uiSettings: [
      AndroidUiSettings(
        toolbarTitle: 'Urban Express Cropper',
        toolbarColor: buttonColor,
        toolbarWidgetColor: Colors.white,
        initAspectRatio: CropAspectRatioPreset.ratio4x3,
        lockAspectRatio: true,
      ),
      IOSUiSettings(
        title: 'Cropper',
      ),
    ],
  );
  if (cropFile != null) {
    return XFile(cropFile.path);
  }
  return null;
}
```
My device is Realme 9 model no RMX3521

**Comment by faizan2301** [comment]
Sorry I forgot to add this code in my manifest
```
 <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
```
