### ISSUE TITLE
App Crashes when crop icon is clicked.

### ISSUE THREAD

**Issue by Shubham555** [hnvn/flutter_image_cropper#5]
Hey there, 

I am facing an issue with image crop plugin, whenever I select an image and click on crop, the app crashes with these logs. 

```
D/EGL_emulation(25038): eglMakeCurrent: 0xe5d84780: ver 3 1 (tinfo 0xe5dff060)
D/EGL_emulation(25038): eglCreateContext: 0xe7c84500: maj 3 min 1 rcv 4
D/EGL_emulation(25038): eglMakeCurrent: 0xe7c84500: ver 3 1 (tinfo 0xe450ad10)
E/eglCodecCommon(25038): glUtilsParamSize: unknow param 0x000082da
E/eglCodecCommon(25038): glUtilsParamSize: unknow param 0x000082da
D/EGL_emulation(25038): eglMakeCurrent: 0xe5d84780: ver 3 1 (tinfo 0xe5dff060)
D/EGL_emulation(25038): eglMakeCurrent: 0xe7c84500: ver 3 1 (tinfo 0xe450adf0)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): Failed to handle method call
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.a3rdflix.menu/com.yalantis.ucrop.UCropActivity}; have you declared this activity in your AndroidManifest.xml?
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2005)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.app.Activity.startActivityForResult(Activity.java:4586)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.app.Activity.startActivityForResult(Activity.java:4544)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:138)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:128)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(ImageCropperDelegate.java:66)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(ImageCropperPlugin.java:36)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.hunghd.vn/image_cropper(25038): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/AndroidRuntime(25038): Shutting down VM
E/AndroidRuntime(25038): FATAL EXCEPTION: main
E/AndroidRuntime(25038): Process: com.a3rdflix.menu, PID: 25038
E/AndroidRuntime(25038): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {com.a3rdflix.menu/com.a3rdflix.menu.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(25038): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4360)
E/AndroidRuntime(25038): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
E/AndroidRuntime(25038): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(25038): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(25038): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(25038): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime(25038): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(25038): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(25038): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(25038): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25038): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(25038): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(25038): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(25038): 	at io.flutter.view.FlutterNativeView$1.reply(FlutterNativeView.java:174)
E/AndroidRuntime(25038): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:194)
E/AndroidRuntime(25038): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:81)
E/AndroidRuntime(25038): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(25038): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(25038): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(25038): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime(25038): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
E/AndroidRuntime(25038): 	... 11 more
E/flutter (25038): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (25038): PlatformException(error, Unable to find explicit activity class {com.a3rdflix.menu/com.yalantis.ucrop.UCropActivity}; have you declared this activity in your AndroidManifest.xml?, null)
E/flutter (25038): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (25038): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter (25038): <asynchronous suspension>
E/flutter (25038): #2      ImageCropper.cropImage (package:image_cropper/image_cropper.dart:34:46)
E/flutter (25038): <asynchronous suspension>
E/flutter (25038): #3      _AnalysisPageState._cropImage (package:menu/AnalysisPage.dart:74:43)
E/flutter (25038): <asynchronous suspension>
E/flutter (25038): #4      _AnalysisPageState.build.<anonymous closure> (package:menu/AnalysisPage.dart:44:9)
E/flutter (25038): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:503:14)
E/flutter (25038): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:558:30)
E/flutter (25038): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (25038): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (25038): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter (25038): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter (25038): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (25038): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter (25038): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:143:19)
E/flutter (25038): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (25038): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (25038): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (25038): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (25038): #18     _invoke1 (dart:ui/hooks.dart:142:13)
E/flutter (25038): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:99:5)
I/Process (25038): Sending signal. PID: 25038 SIG: 9
Application finished.
```

**Comment by hnvn** [comment]
Sounds like you don't declare UCropActivity on your Manifest of Android project, see Android integration for details
