### ISSUE TITLE
[ANDROID] Crash app when cancel crop 

### ISSUE THREAD

**Issue by anhdo9797** [hnvn/flutter_image_cropper#510]
Every time I pressed the close button when snipping the screen, the app crashed with the following error:

```
E/AndroidRuntime(23450): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {***.app/***.MainActivity}: java.lang.NullPointerException: Parameter specified as non-null is null: method ***.MainActivity.onActivityResult, parameter data
E/AndroidRuntime(23450): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4633)
E/AndroidRuntime(23450): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4675)
E/AndroidRuntime(23450): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(23450): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(23450): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(23450): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
E/AndroidRuntime(23450): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(23450): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(23450): 	at android.app.ActivityThread.main(ActivityThread.java:7073)
E/AndroidRuntime(23450): 	at java.lang.reflect.Method.invoke(Native Method)

```

My dependencies:
- Flutter 3.19.6
- image_cropper: "7.1.0"

<img width="456" alt="Screenshot 2024-07-18 at 9 55 53 AM" src="https://github.com/user-attachments/assets/24d04afb-9cd3-4ae8-86e2-d7cea1b7896c">

**Comment by doggybell-tech** [comment]
have the same problem. also on iOS.
