### ISSUE TITLE
`NullPointerException` in `UCropActivity` during `onCreateOptionsMenu()` causing crash in release mode

### ISSUE THREAD

**Issue by mbfakourii** [hnvn/flutter_image_cropper#544]
**Description**

The app crashes with a NullPointerException in the UCropActivity during the onCreateOptionsMenu() method, but only in release mode. This issue does not occur in debug mode.

```dart
FATAL EXCEPTION: main
                 Process: com.example.app, PID: 4046
                 java.lang.NullPointerException: throw with null exception
                 	at m.i.inflate(SourceFile:25)
                 	at com.yalantis.ucrop.UCropActivity.onCreateOptionsMenu(SourceFile:7)
                 	at android.app.Activity.onCreatePanelMenu(Activity.java:4228)
                 	at e.n.onCreatePanelMenu(SourceFile:3)
                 	at j.y.onCreatePanelMenu(SourceFile:11)
                 	at e.j.run(SourceFile:925)
                 	at android.os.Handler.handleCallback(Handler.java:888)
                 	at android.os.Handler.dispatchMessage(Handler.java:100)
                 	at android.os.Looper.loop(Looper.java:213)
                 	at android.app.ActivityThread.main(ActivityThread.java:8178)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Additional Information**
settings.gradle:
```
id "com.android.application" version "8.2.1" apply false
```

gradle-wrapper.properties:
```dart
distributionUrl=https\://services.gradle.org/distributions/gradle-8.3-all.zip
```

Other:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.27.1, on Microsoft Windows [Version 10.0.26100.2454], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.11.5)
[√] Android Studio (version 2024.2)
[√] Connected device (5 available)
[√] Network resources
```

**Comment by mbfakourii** [comment]
```dart
buildTypes {
    release {
        minifyEnabled false
        shrinkResources false
        signingConfig signingConfigs.release
    }
}
```

I solved the problem with this code, but the program size increased by 7 MB!

**Comment by GuimG** [comment]
@mbfakourii works for me too, thanks.

**Comment by hnvn** [comment]
add following lines to your `android/app/proguard-rules.pro`:
```
-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }
```

**Comment by mbfakourii** [comment]
> add following lines to your `android/app/proguard-rules.pro`:
> 
> ```
> -dontwarn com.yalantis.ucrop**
> -keep class com.yalantis.ucrop** { *; }
> -keep interface com.yalantis.ucrop** { *; }
> ```
> 
> Fyi why it happened? https://developer.android.com/build/shrink-code

I tested it and it didn't work.

**Comment by inpt333** [comment]
> add following lines to your `android/app/proguard-rules.pro`:
> 
> ```
> -dontwarn com.yalantis.ucrop**
> -keep class com.yalantis.ucrop** { *; }
> -keep interface com.yalantis.ucrop** { *; }
> ```
> 
> Fyi why it happened? https://developer.android.com/build/shrink-code

@hnvn it seems that those are not enough, it didn't work for me either.

**Comment by vinay-elred** [comment]
Using this : Working for me now
https://github.com/hnvn/flutter_image_cropper/issues/544#issuecomment-2558412236

@hnvn Can you please confirm by when can except this fix.

**Comment by 0x3dev** [comment]
@vinay-elred just tried the proguard rules now, unfortunately it doesn't solve it

**Comment by MrLightful** [comment]
Still an issue.

**Comment by fullflash** [comment]
sad to see that still this issue has not been resolved only working with debug mode not release.

**Comment by MrLightful** [comment]
> sad to see that still this issue has not been resolved only working with debug mode not release.

I'd say it should be solved, but not by this package, but an android native package used internally. This package is just a flutter wrapper.

https://github.com/Yalantis/uCrop/issues/913

**Comment by nfriend** [comment]
Just ran into this in March of 2025 on version `9.0.0`. The fix [described above](https://github.com/hnvn/flutter_image_cropper/issues/544#issuecomment-2558412236) worked for me 👍

**Comment by rahdeva** [comment]
April and still an issue.

**Comment by rahdeva** [comment]
Changing the following line in `gradle.properties` works for me:

```properties
android.enableR8.fullMode=false
```

This is better than disabling minification and resource shrinking completely, so I still keep these set to `true`:

```groovy
minifyEnabled true
shrinkResources true
```

**Comment by json-kim** [comment]
Adding the following to the proguard-rules.pro file solved my issue

```
-dontwarn org.xmlpull.v1.**
-keep class org.xmlpull.v1.** { *; }
```

**Comment by yizaho** [comment]
> Changing the following line in `gradle.properties` works for me:
> 
> `android.enableR8.fullMode=false`
> This is better than disabling minification and resource shrinking completely, so I still keep these set to `true`:

Used above as a temporary solution. @hnvn  Any outlook on a fix?

**Comment by edex96** [comment]
I made it work as below as of now 🦧

I copied detailed error logs to gemini and it created fine tuned exceptions for my project 😇

`./android/app/build.gradle.kts`
```
...
 buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
            proguardFiles(
                 // File with default rules provided by the Android Gradle Plugin
                getDefaultProguardFile("proguard-android-optimize.txt"),
                // File with your custom rules
                "proguard-rules.pro"
            )
        }
    }
...
````


`./android/app/proguard-rules.pro`
```pro
# R8/ProGuard Rules for OkHttp and Okio (Needed by uCrop or similar dependencies)

-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-keep public class okio.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**

# Optional: You might also need rules for the library referencing them (uCrop)
-keep class com.yalantis.ucrop.** { *; }
-dontwarn com.yalantis.ucrop.**
```
