### ISSUE TITLE
Flutter 1.7 Android when crop icon , App Crashes

### ISSUE THREAD

**Issue by Scofielddd** [hnvn/flutter_image_cropper#65]
```
Launching lib\main.dart on Redmi 5 Plus in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/zygote64(26023): Do partial code cache collection, code=30KB, data=20KB
I/zygote64(26023): After code cache collection, code=30KB, data=20KB
I/zygote64(26023): Increasing code cache capacity to 128KB
I/zygote64(26023): Rejecting re-init on previously-failed class java.lang.Class<com.yalantis.ucrop.UCropActivity>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
I/zygote64(26023):   at android.content.Intent com.yalantis.ucrop.UCrop.getIntent(android.content.Context) (UCrop.java:186)
I/zygote64(26023):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity, int) (UCrop.java:138)
I/zygote64(26023):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity) (UCrop.java:128)
I/zygote64(26023):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:91)
I/zygote64(26023):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:42)
I/zygote64(26023):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:222)
I/zygote64(26023):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:96)
I/zygote64(26023):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:643)
I/zygote64(26023):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(26023):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:331)
I/zygote64(26023):   at void android.os.Looper.loop() (Looper.java:149)
I/zygote64(26023):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6651)
I/zygote64(26023):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(26023):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/zygote64(26023):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:824)
I/zygote64(26023): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64, /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
I/zygote64(26023):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:125)
I/zygote64(26023):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(26023):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(26023):   at android.content.Intent com.yalantis.ucrop.UCrop.getIntent(android.content.Context) (UCrop.java:186)
I/zygote64(26023):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity, int) (UCrop.java:138)
I/zygote64(26023):   at void com.yalantis.ucrop.UCrop.start(android.app.Activity) (UCrop.java:128)
I/zygote64(26023):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperDelegate.java:91)
I/zygote64(26023):   at void vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (ImageCropperPlugin.java:42)
I/zygote64(26023):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:222)
I/zygote64(26023):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:96)
I/zygote64(26023):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:643)
I/zygote64(26023):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/zygote64(26023):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:331)
I/zygote64(26023):   at void android.os.Looper.loop() (Looper.java:149)
I/zygote64(26023):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6651)
I/zygote64(26023):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/zygote64(26023):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:547)
I/zygote64(26023):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:824)
I/zygote64(26023):
E/flutter (26023): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yalantis/ucrop/UCropActivity;
E/flutter (26023): 	at com.yalantis.ucrop.UCrop.getIntent(UCrop.java:186)
E/flutter (26023): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:138)
E/flutter (26023): 	at com.yalantis.ucrop.UCrop.start(UCrop.java:128)
E/flutter (26023): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.startCrop(ImageCropperDelegate.java:91)
E/flutter (26023): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperPlugin.onMethodCall(ImageCropperPlugin.java:42)
E/flutter (26023): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter (26023): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (26023): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/flutter (26023): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (26023): 	at android.os.MessageQueue.next(MessageQueue.java:331)
E/flutter (26023): 	at android.os.Looper.loop(Looper.java:149)
E/flutter (26023): 	at android.app.ActivityThread.main(ActivityThread.java:6651)
E/flutter (26023): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (26023): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter (26023): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
E/flutter (26023): Caused by: java.lang.ClassNotFoundException: com.yalantis.ucrop.UCropActivity
E/flutter (26023): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/flutter (26023): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/flutter (26023): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/flutter (26023): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (26023): 	... 15 more
E/flutter (26023): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/app/AppCompatActivity;
E/flutter (26023): 	... 15 more
E/flutter (26023): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64, /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/flutter (26023): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/flutter (26023): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (26023): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (26023): 	... 15 more
E/flutter (26023):
F/flutter (26023): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
F/libc    (26023): Fatal signal 6 (SIGABRT), code -6 in tid 26023 (e.flutter_vayes), pid 26023 (e.flutter_vayes)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/vince/vince:8.1.0/OPM1.171019.019/V10.2.1.0.OEGMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 26023, tid: 26023, name: e.flutter_vayes  >>> com.example.flutter_vayes <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env).
'
    x0   0000000000000000  x1   00000000000065a7  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000000  x5   0000000000000000  x6   0000000000000000  x7   0000000000800000
    x8   0000000000000083  x9   f4422b9262d89c59  x10  0000000000000000  x11  0000000000000001
    x12  ffffffffffffffff  x13  0000000000000028  x14  ffffffffffffffff  x15  00007d8ebda9dcf4
    x16  0000005809ce0fa8  x17  0000007308e8e5d8  x18  0000000000000000  x19  00000000000065a7
    x20  00000000000065a7  x21  0000007ffdee4a78  x22  000000726954f0b0  x23  000000726a1fb1f0
    x24  000000000000002d  x25  0000000000000001  x26  0000007276eb3580  x27  0000007286ad3008
    x28  00000073072c7f88  x29  0000007ffdee4a60  x30  0000007308e43e38
    sp   0000007ffdee4a20  pc   0000007308e43e54  pstate 0000000060000000
backtrace:
    #00 pc 000000000001de54  /system/lib64/libc.so (abort+104)
    #01 pc 0000000000d34a40  /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64/libflutter.so (offset 0xd20000)
    #02 pc 0000000000d2778c  /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64/libflutter.so (offset 0xd20000)
    #03 pc 0000000000d25cb0  /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64/libflutter.so (offset 0xd20000)
    #04 pc 0000000000d6c078  /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64/libflutter.so (offset 0xd20000)
    #05 pc 0000000000d354ec  /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64/libflutter.so (offset 0xd20000)
    #06 pc 0000000000d3a1f4  /data/app/com.example.flutter_vayes-1RJMST85BQ-YzW65KGIVMA==/lib/arm64/libflutter.so (offset 0xd20000)
    #07 pc 0000000000016144  /system/lib64/libutils.so (android::Looper::pollInner(int)+1000)
    #08 pc 0000000000015cd4  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+108)
    #09 pc 000000000011b6c8  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
    #10 pc 0000000000811adc  /system/framework/arm64/boot-framework.oat (offset 0x62b000) (android.app.NativeActivity.onWindowFocusChangedNative [DEDUPED]+140)
    #11 pc 0000000000008498  /dev/ashmem/dalvik-jit-code-cache (deleted)
Lost connection to device.
Exited (sigterm)

```

as same main.dart in example and new project

**Comment by Scofielddd** [comment]
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutter_vayes">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="flutter_vayes"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
        </activity>
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
    </application>
</manifest>

```

**Comment by Scofielddd** [comment]
i fixed

```
org.gradle.jvmargs=-Xmx1536M
android.enableJetifier=true
android.useAndroidX=true
```
