### ISSUE TITLE
The problem of about v1.10 ~~~ Help!

### ISSUE THREAD

**Issue by originlan** [hnvn/flutter_image_cropper#77]
First of all, thank you very much for the update of the Widget. However, I found a problem today. After selecting the picture, my project will report this error. thanks

> 2019-09-30 17:53:22.155 30223-30223/com.aaa.aaa E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.aaa.aaa, PID: 30223
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:453)
        at java.lang.Class.forName(Class.java:378)
        at com.growingio.android.sdk.utils.ClassExistHelper.hasClass(ClassExistHelper.java:77)
        at com.growingio.android.sdk.utils.ClassExistHelper.<clinit>(ClassExistHelper.java:61)
        at com.growingio.android.sdk.utils.ClassExistHelper.issHasAdvertisingIdClient(ClassExistHelper.java:117)
        at com.growingio.android.sdk.collection.DeviceUUIDFactory.initGoogleAdId(DeviceUUIDFactory.java:209)
        at com.growingio.android.sdk.collection.DeviceUUIDFactory.getGoogleAdId(DeviceUUIDFactory.java:227)
        at com.growingio.android.sdk.models.VisitEvent.backgroundWorker(VisitEvent.java:131)
        at com.growingio.android.sdk.data.DataSubscriber.saveMessage(DataSubscriber.java:102)
        at com.growingio.android.sdk.data.DataSubscriber.onGIOEvent(DataSubscriber.java:72)
        at com.growingio.android.sdk.data.DataSubscriber.do$Action(Unknown Source:41)
        at com.growingio.eventcenter.bus.Subscription.action(Subscription.java:54)
        at com.growingio.eventcenter.bus.EventBus.invokeSubscriber(EventBus.java:579)
        at com.growingio.eventcenter.bus.EventBus.invokeSubscriber(EventBus.java:574)
        at com.growingio.eventcenter.bus.BackgroundPoster.run(BackgroundPoster.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/data/app/com.aaa.aaa-5Y_nKZKct5ewxAIXhMIb-g==/base.apk"],nativeLibraryDirectories=[/data/app/com.aaa.aaa-5Y_nKZKct5ewxAIXhMIb-g==/lib/arm64, /data/app/com.aaa.aaa-5Y_nKZKct5ewxAIXhMIb-g==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:453) 
        at java.lang.Class.forName(Class.java:378) 
        at com.growingio.android.sdk.utils.ClassExistHelper.hasClass(ClassExistHelper.java:77) 
        at com.growingio.android.sdk.utils.ClassExistHelper.<clinit>(ClassExistHelper.java:61) 
        at com.growingio.android.sdk.utils.ClassExistHelper.issHasAdvertisingIdClient(ClassExistHelper.java:117) 
        at com.growingio.android.sdk.collection.DeviceUUIDFactory.initGoogleAdId(DeviceUUIDFactory.java:209) 
        at com.growingio.android.sdk.collection.DeviceUUIDFactory.getGoogleAdId(DeviceUUIDFactory.java:227) 
        at com.growingio.android.sdk.models.VisitEvent.backgroundWorker(VisitEvent.java:131) 
        at com.growingio.android.sdk.data.DataSubscriber.saveMessage(DataSubscriber.java:102) 
        at com.growingio.android.sdk.data.DataSubscriber.onGIOEvent(DataSubscriber.java:72) 
        at com.growingio.android.sdk.data.DataSubscriber.do$Action(Unknown Source:41) 
        at com.growingio.eventcenter.bus.Subscription.action(Subscription.java:54) 
        at com.growingio.eventcenter.bus.EventBus.invokeSubscriber(EventBus.java:579) 
        at com.growingio.eventcenter.bus.EventBus.invokeSubscriber(EventBus.java:574) 
        at com.growingio.eventcenter.bus.BackgroundPoster.run(BackgroundPoster.java:64) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 

doctor

> Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.1-pre.41, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
⢿       
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

**Comment by originlan** [comment]
I don't quite understand why I think this LifecycleEventObserver is true，I have already add
the 

> 
android{
  configurations.all {
        resolutionStrategy {
            force 'androidx.media:media:1.0.0'
            force "androidx.lifecycle:lifecycle-runtime:2.1.0"
        }
    }
}
implementation "androidx.core:core:1.1.0"

    implementation 'androidx.lifecycle:lifecycle-runtime:2.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0'
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.0.0'
    annotationProcessor  'androidx.lifecycle:lifecycle-compiler:2.0.0'
angthing!

**Comment by hnvn** [comment]
`gradle.properties`
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by originlan** [comment]
I have alreay 
org.gradle.jvmargs=-Xmx1536M
android.enableJetifier=true
android.useAndroidX=true
#android.enableR8=true

**Comment by hnvn** [comment]
try this: https://github.com/flutter/flutter/issues/34401

**Comment by originlan** [comment]
> try this: [flutter/flutter#34401](https://github.com/flutter/flutter/issues/34401)

Still won't work

**Comment by originlan** [comment]
but,different to err

> 2019-10-01 00:39:07.613 10142-10142/com.yueli.sc_flutter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yueli.sc_flutter, PID: 10142
    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleRegistry;
        at androidx.core.app.ComponentActivity.<init>(ComponentActivity.java:56)
        at androidx.activity.ComponentActivity.<init>(ComponentActivity.java:84)
        at androidx.fragment.app.FragmentActivity.<init>(FragmentActivity.java:127)
        at androidx.appcompat.app.AppCompatActivity.<init>(AppCompatActivity.java:77)
        at com.yalantis.ucrop.UCropActivity.<init>(UCropActivity.java:63)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1243)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleRegistry" on path: DexPathList[[zip file "/data/app/com.yueli.sc_flutter-9uC4M1ORZFKY1n983fv4pQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.yueli.sc_flutter-9uC4M1ORZFKY1n983fv4pQ==/lib/x86, /data/app/com.yueli.sc_flutter-9uC4M1ORZFKY1n983fv4pQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at androidx.core.app.ComponentActivity.<init>(ComponentActivity.java:56) 
        at androidx.activity.ComponentActivity.<init>(ComponentActivity.java:84) 
        at androidx.fragment.app.FragmentActivity.<init>(FragmentActivity.java:127) 
        at androidx.appcompat.app.AppCompatActivity.<init>(AppCompatActivity.java:77) 
        at com.yalantis.ucrop.UCropActivity.<init>(UCropActivity.java:63) 
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1243) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3182) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by hnvn** [comment]
Can you reproduce this issue on the example project?

**Comment by hnvn** [comment]
It seems like #78

**Comment by originlan** [comment]
Yes，example is the work，so It's my engineering that's not compatible with it

**Comment by originlan** [comment]
look 

> def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 29

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.yueli.sc_flutter"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true

        resValue("string", "growingio_project_id", "bafa3c0ce0c99cfd")
        resValue("string", "growingio_url_scheme", "growing.a7daea56bfc43525")
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }

//        debug {
//            keyAlias keystoreProperties['soucang']
//            keyPassword keystoreProperties['bVTvsaLwxtXBoxbtmduwPsK7']
//            storeFile file(keystoreProperties['storeFile'])
//            storePassword keystoreProperties['bVTvsaLwxtXBoxbtmduwPsK7']
//        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            useProguard false
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }


}

flutter {
    source '../..'
}


dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.king.app:app-updater:1.0.4-androidx'
    implementation 'com.growingio.android:vds-android-agent:track-2.8.0@aar'

//    implementation 'com.umeng.umsdk:share-core:6.9.6'
    implementation 'com.umeng.umsdk:share-wx:6.9.4'

    implementation "androidx.core:core:1.1.0"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'



}

**Comment by jasonlaw** [comment]
> Yes，example is the work，so It's my engineering that's not compatible with it

Hi @originlan, 
Have you resolved the problem? May I know how did you fix it?
Thanks in advance.

**Comment by originlan** [comment]
> > Yes，example is the work，so It's my engineering that's not compatible with it
> 
> Hi @originlan,
> Have you resolved the problem? May I know how did you fix it?
> Thanks in advance.

sorry,It not fix to me

**Comment by jasonlaw** [comment]
It works well with a new create project, of course it is just a simple one. I tried to replace android folder from the new simple project (I have made all settings compatible to my project, and make sure the simple project still work under the settings), but still getting the same error. I have totally run out of ideas. Any help or advice is highly appreciated.

**Comment by yevgeniaronov** [comment]
@originlan 
@jasonlaw 
i have the same issue as you, i fixed it (but it throws some errors regarding my cloud_firestore dependencies now in the console, but it works).

the 2 ways i found are upgrading gradle and kotlin (root build.gradle):
`
ext.kotlin_version = '1.3.0'
classpath 'com.android.tools.build:gradle:3.3.1'
`

or pasting this voodoo in your app/build.grade:
https://stackoverflow.com/a/54923461
