### ISSUE TITLE
java.lang.IllegalArgumentException: Unsupported value: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()

### ISSUE THREAD

**Issue by JCKodel** [hnvn/flutter_image_cropper#95]
java.lang.IllegalArgumentException: Unsupported value: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
    at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
    at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
    at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.finishWithError(ImageCropperDelegate.java:120)
    at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:103)
    at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
    at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
    at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
    at android.app.Activity.dispatchActivityResult(Activity.java:6867)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4729)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4776)
    at android.app.ActivityThread.access$1500(ActivityThread.java:218)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1767)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6917)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=96, data=Intent { (has extras) }} to activity {br.art.code.meucronogramacapilar/br.art.code.meucronogramacapilar.MainActivity}: java.lang.IllegalArgumentException: Unsupported value: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4733)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4776)
    at android.app.ActivityThread.access$1500(ActivityThread.java:218)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1767)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6917)
    at java.lang.reflect.Method.invoke(Method.java)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

Don't have context because it is an automated Sentry caught exception.

**Comment by randhika** [comment]
Any update for this issue guys? same happens in here

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=96, data=Intent { (has extras) }} to activity {MainActivity}: java.lang.IllegalArgumentException: Unsupported value: java.lang.IllegalArgumentException: x + width must be <= bitmap.width()
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3945)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3988)
       at android.app.ActivityThread.access$1400(ActivityThread.java:188)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1579)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5839)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
```

**Comment by huma11farheen** [comment]
@randhika 
i made an issue with a possible solution

**Comment by sujindra-kodiary** [comment]
Any solution to this issue?
